apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: veritrail-data
  namespace: veritrail
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
